import { withSentryConfig } from "@sentry/nextjs";
import type { NextConfig } from "next";
import { withWorkflow } from "workflow/next";

const nextConfig = {
  output: "standalone",
  // start custom keeperhub code //
  // The SDK loads @workflow/world-postgres via dynamic
  // require(process.env.WORKFLOW_TARGET_WORLD) which the standalone output
  // tracer cannot follow. serverExternalPackages keeps it out of the bundle
  // and outputFileTracingIncludes forces it into the standalone node_modules.
  // .npmrc public-hoist-pattern hoists these from .pnpm/ to top-level
  // node_modules/ so the simple globs below can find them.
  // Full transitive dependency tree of @workflow/world-postgres.
  // Generated by: node scripts/list-world-deps.mjs
  serverExternalPackages: [
    "@vercel/oidc",
    "@vercel/queue",
    "@workflow/errors",
    "@workflow/utils",
    "@workflow/world",
    "@workflow/world-local",
    "@workflow/world-postgres",
    "async-sema",
    "cbor-x",
    "cron-parser",
    "dotenv",
    "drizzle-orm",
    "luxon",
    "mixpart",
    "ms",
    "pg",
    "pg-boss",
    "pg-connection-string",
    "pg-int8",
    "pg-pool",
    "pg-protocol",
    "pg-types",
    "pgpass",
    "postgres",
    "postgres-array",
    "postgres-bytea",
    "postgres-date",
    "postgres-interval",
    "serialize-error",
    "split2",
    "type-fest",
    "ulid",
    "undici",
    "xtend",
    "zod",
  ],
  outputFileTracingIncludes: {
    "/*": [
      "./node_modules/@vercel/oidc/**/*",
      "./node_modules/@vercel/queue/**/*",
      "./node_modules/@workflow/errors/**/*",
      "./node_modules/@workflow/utils/**/*",
      "./node_modules/@workflow/world/**/*",
      "./node_modules/@workflow/world-local/**/*",
      "./node_modules/@workflow/world-postgres/**/*",
      "./node_modules/async-sema/**/*",
      "./node_modules/cbor-x/**/*",
      "./node_modules/cbor-extract/**/*",
      "./node_modules/cron-parser/**/*",
      "./node_modules/dotenv/**/*",
      "./node_modules/drizzle-orm/**/*",
      "./node_modules/luxon/**/*",
      "./node_modules/mixpart/**/*",
      "./node_modules/ms/**/*",
      "./node_modules/pg/**/*",
      "./node_modules/pg-boss/**/*",
      "./node_modules/pg-connection-string/**/*",
      "./node_modules/pg-int8/**/*",
      "./node_modules/pg-pool/**/*",
      "./node_modules/pg-protocol/**/*",
      "./node_modules/pg-types/**/*",
      "./node_modules/pgpass/**/*",
      "./node_modules/postgres/**/*",
      "./node_modules/postgres-array/**/*",
      "./node_modules/postgres-bytea/**/*",
      "./node_modules/postgres-date/**/*",
      "./node_modules/postgres-interval/**/*",
      "./node_modules/serialize-error/**/*",
      "./node_modules/split2/**/*",
      "./node_modules/type-fest/**/*",
      "./node_modules/ulid/**/*",
      "./node_modules/undici/**/*",
      "./node_modules/xtend/**/*",
      "./node_modules/zod/**/*",
      "./node_modules/next/dist/compiled/@vercel/og/**/*",
    ],
  },
  // end keeperhub code //
  logging: {
    fetches: {
      fullUrl: true,
    },
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "raw.githubusercontent.com",
        pathname: "/trustwallet/assets/**",
      },
    ],
  },
} satisfies NextConfig & { eslint?: { ignoreDuringBuilds?: boolean } };

const { SENTRY_ORG, SENTRY_PROJECT } = process.env;

export default withSentryConfig(withWorkflow(nextConfig), {
  // For all available options, see:
  // https://www.npmjs.com/package/@sentry/webpack-plugin#options

  org: SENTRY_ORG,
  project: SENTRY_PROJECT,

  // Only print logs for uploading source maps in CI
  silent: !process.env.CI,

  // For all available options, see:
  // https://docs.sentry.io/platforms/javascript/guides/nextjs/manual-setup/

  // Upload a larger set of source maps for prettier stack traces (increases build time)
  widenClientFileUpload: true,

  // Route browser requests to Sentry through a Next.js rewrite to circumvent ad-blockers.
  // This can increase your server load as well as your hosting bill.
  // Note: Check that the configured route will not match with your Next.js middleware, otherwise reporting of client-
  // side errors will fail.
  tunnelRoute: "/monitoring",

  webpack: {
    // Enables automatic instrumentation of Vercel Cron Monitors. (Does not yet work with App Router route handlers.)
    // See the following for more information:
    // https://docs.sentry.io/product/crons/
    // https://vercel.com/docs/cron-jobs
    automaticVercelMonitors: true,

    // Tree-shaking options for reducing bundle size
    treeshake: {
      // Automatically tree-shake Sentry logger statements to reduce bundle size
      removeDebugLogging: true,
    },
  },
});
