/**
 * KeeperHub Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * KeeperHub-specific plugins that extend the base workflow builder.
 * These plugins are loaded in addition to the base plugins.
 *
 * Discovered plugins: discord, math, sendgrid, telegram, web3, webhook
 */

import "./discord";
import "./math";
import "./sendgrid";
import "./telegram";
import "./web3";
import "./webhook";

// Re-export types from base registry for convenience
export type {
  ActionConfigField,
  ActionConfigFieldBase,
  ActionConfigFieldGroup,
  ActionWithFullId,
  IntegrationPlugin,
  PluginAction,
} from "@/plugins/registry";

export {
  computeActionId,
  findActionById,
  flattenConfigFields,
  generateAIActionPrompts,
  getActionsByCategory,
  getAllActions,
  getAllDependencies,
  getAllEnvVars,
  getAllIntegrations,
  getCredentialMapping,
  getDependenciesForActions,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getPluginEnvVars,
  getSortedIntegrationTypes,
  isFieldGroup,
  parseActionId,
  registerIntegration,
} from "@/plugins/registry";
