// Monaco editor theme configuration for Vercel-like dark mode
export const vercelDarkTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "", foreground: "D4D4D4" },
    { token: "comment", foreground: "666666", fontStyle: "italic" },
    { token: "keyword", foreground: "FF6AC1" },
    { token: "string", foreground: "FF6AC1" },
    { token: "number", foreground: "79C0FF" },
    { token: "regexp", foreground: "FF6AC1" },
    { token: "type", foreground: "79C0FF" },
    { token: "class", foreground: "79C0FF" },
    { token: "function", foreground: "D4D4D4" },
    { token: "variable", foreground: "D4D4D4" },
    { token: "constant", foreground: "79C0FF" },
    { token: "operator", foreground: "D4D4D4" },
    { token: "delimiter", foreground: "D4D4D4" },
  ],
  colors: {
    "editor.background": "#000000",
    "editor.foreground": "#D4D4D4",
    "editorLineNumber.foreground": "#444444",
    "editorLineNumber.activeForeground": "#888888",
    "editor.lineHighlightBackground": "#0A0A0A",
    "editor.selectionBackground": "#264F78",
    "editor.inactiveSelectionBackground": "#1A1A1A",
    "editorCursor.foreground": "#FFFFFF",
    "editorWhitespace.foreground": "#333333",
    "editorIndentGuide.background": "#1A1A1A",
    "editorIndentGuide.activeBackground": "#333333",
    "editorBracketMatch.background": "#0A0A0A",
    "editorBracketMatch.border": "#444444",
  },
};
