/**
 * Protocol Definitions Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Imports all protocol definitions and registers them at import time.
 * This ensures the protocol registry is populated when the Next.js
 * server starts (via the plugin import chain).
 *
 * Registered protocols: weth
 */

import {
  protocolToPlugin,
  registerProtocol,
} from "@/keeperhub/lib/protocol-registry";
import { registerIntegration } from "@/plugins/registry";

import wethDef from "./weth";

registerProtocol(wethDef);
registerIntegration(protocolToPlugin(wethDef));
